server:
  port: 8081

spring:
  application:
    name: maple-service

  profiles:
    include: infra

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
#      sentinel:
#        master: mymaster
#        nodes:
#          - ${redis.sentinel-1}
#          - ${redis.sentinel-2}
#          - ${redis.sentinel-3}
#        password: ${redis.password}

logging:
  level:
    com.maple.mapleservice: debug
