server:
  port: 8081
spring:
  application:
    name: maple-service
  profiles:
    include: infra

  datasource:
    url:
    driver-class-name:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ${redis.password}
logging:
  level:
    com.maple.mapleservice: debug
