server:
  port: 8080

spring:
  application:
    name: dnf-service

  profiles:
    include: infra

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          trace

cloudfront:
  utl: ${cloudfront.url}