server:
  port: 8080

spring:
  application:
    name: dnf-service

  profiles:
    include: infra

  cache:
    type: redis

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          trace
