server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}
    hostname: ${eureka.host}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${redis.host}:8761/eureka


spring:
  application:
    name: api-gateway-service

  profiles:
    include: infra

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        - id: maple-service
          uri: lb://MAPLE-SERVICE
          predicates:
            - Path=/maple-service/**
          filters:
            - CustomFilter